import type { Flight, Gate, Runway, SimState, Weather } from "./types";

const RUNWAYS: Runway[] = [
  { id: "28L", headingDeg: 281, lengthFt: 11381, mode: "arrivals", surfaceFriction: "dry" },
  { id: "28R", headingDeg: 281, lengthFt: 11870, mode: "arrivals", surfaceFriction: "dry" },
  { id: "01L", headingDeg: 14, lengthFt: 7650, mode: "departures", surfaceFriction: "dry" },
  { id: "01R", headingDeg: 14, lengthFt: 8650, mode: "departures", surfaceFriction: "dry" },
];

const GATES: Gate[] = [
  { id: "A1", terminal: "T1", maxWake: "medium" },
  { id: "A2", terminal: "T1", maxWake: "heavy" },
  { id: "A3", terminal: "T1", maxWake: "heavy" },
  { id: "B1", terminal: "T2", maxWake: "heavy" },
  { id: "B2", terminal: "T2", maxWake: "super" },
  { id: "B3", terminal: "T2", maxWake: "super" },
  { id: "C1", terminal: "T3", maxWake: "medium" },
  { id: "C2", terminal: "T3", maxWake: "medium" },
  { id: "C3", terminal: "T3", maxWake: "heavy" },
  { id: "D1", terminal: "T4", maxWake: "heavy" },
];

const WEATHER: Weather = {
  windDirDeg: 270,
  windKts: 14,
  gustsKts: 22,
  visibilityNm: 8,
  ceilingFt: 4500,
  condition: "VFR",
  precipitation: "none",
};

const SEED_FLIGHTS: Flight[] = [
  {
    id: "f1",
    callsign: "UAL228",
    type: "arrival",
    aircraft: "B789",
    wake: "heavy",
    origin: "EGLL",
    destination: "KSFO",
    phase: "approach",
    altitudeFt: 4200,
    speedKts: 210,
    headingDeg: 281,
    positionNm: { x: 18, y: 2 },
    assignedRunway: "28L",
    assignedGate: "B2",
    fuelMin: 95,
    etaMin: 9,
    squawk: "2401",
  },
  {
    id: "f2",
    callsign: "DAL512",
    type: "arrival",
    aircraft: "A321",
    wake: "medium",
    origin: "KATL",
    destination: "KSFO",
    phase: "approach",
    altitudeFt: 5100,
    speedKts: 230,
    headingDeg: 281,
    positionNm: { x: 22, y: -4 },
    assignedRunway: "28L",
    assignedGate: "A2",
    fuelMin: 80,
    etaMin: 12,
    squawk: "2402",
  },
  {
    id: "f3",
    callsign: "AAL77",
    type: "arrival",
    aircraft: "B77W",
    wake: "heavy",
    origin: "RJTT",
    destination: "KSFO",
    phase: "final",
    altitudeFt: 1800,
    speedKts: 160,
    headingDeg: 281,
    positionNm: { x: 8, y: 1 },
    assignedRunway: "28R",
    assignedGate: "B3",
    fuelMin: 70,
    etaMin: 4,
    squawk: "2403",
  },
  {
    id: "f4",
    callsign: "SWA1432",
    type: "arrival",
    aircraft: "B738",
    wake: "medium",
    origin: "KLAX",
    destination: "KSFO",
    phase: "enroute",
    altitudeFt: 11000,
    speedKts: 380,
    headingDeg: 320,
    positionNm: { x: 45, y: 18 },
    assignedRunway: "28R",
    assignedGate: "C1",
    fuelMin: 85,
    etaMin: 22,
    squawk: "2404",
  },
  {
    id: "f5",
    callsign: "FDX901",
    type: "arrival",
    aircraft: "B763",
    wake: "heavy",
    origin: "KMEM",
    destination: "KSFO",
    phase: "approach",
    altitudeFt: 6000,
    speedKts: 240,
    headingDeg: 270,
    positionNm: { x: 30, y: 8 },
    assignedRunway: "28L",
    fuelMin: 82,
    etaMin: 14,
    squawk: "2405",
  },
  {
    id: "f6",
    callsign: "UAL901",
    type: "departure",
    aircraft: "B739",
    wake: "medium",
    origin: "KSFO",
    destination: "KEWR",
    phase: "taxi-out",
    altitudeFt: 0,
    speedKts: 12,
    headingDeg: 14,
    positionNm: { x: -2, y: -3 },
    assignedRunway: "01R",
    assignedGate: "A3",
    fuelMin: 360,
    etaMin: 0,
    squawk: "2410",
  },
  {
    id: "f7",
    callsign: "ASA88",
    type: "departure",
    aircraft: "B739",
    wake: "medium",
    origin: "KSFO",
    destination: "PANC",
    phase: "queued",
    altitudeFt: 0,
    speedKts: 0,
    headingDeg: 14,
    positionNm: { x: -1, y: -2 },
    assignedRunway: "01L",
    fuelMin: 420,
    etaMin: 0,
    squawk: "2411",
  },
  {
    id: "f8",
    callsign: "JBU621",
    type: "departure",
    aircraft: "A320",
    wake: "medium",
    origin: "KSFO",
    destination: "KJFK",
    phase: "at-gate",
    altitudeFt: 0,
    speedKts: 0,
    headingDeg: 0,
    positionNm: { x: 0, y: 0 },
    assignedRunway: "01R",
    assignedGate: "C3",
    fuelMin: 380,
    etaMin: 0,
    squawk: "2412",
  },
  {
    id: "f9",
    callsign: "SKW3301",
    type: "arrival",
    aircraft: "E75L",
    wake: "medium",
    origin: "KPDX",
    destination: "KSFO",
    phase: "approach",
    altitudeFt: 3800,
    speedKts: 200,
    headingDeg: 281,
    positionNm: { x: 14, y: -2 },
    assignedRunway: "28R",
    assignedGate: "C2",
    fuelMin: 68,
    etaMin: 7,
    squawk: "2406",
  },
];

const occupy = (gates: Gate[]): Gate[] => {
  const copy = gates.map((g) => ({ ...g }));
  const aGate = copy.find((g) => g.id === "C3");
  if (aGate) aGate.occupiedBy = "f8";
  return copy;
};

export const seedState = (): SimState => ({
  tick: 0,
  clockMin: 14 * 60 + 32,
  sectorId: "KSFO TWR",
  flights: SEED_FLIGHTS,
  runways: RUNWAYS,
  gates: occupy(GATES),
  weather: WEATHER,
  alerts: [],
  speed: 1,
  trails: {},
});
