/**
 * Runway end coordinates for every strip in the registry, WGS-84 degrees.
 *
 * Sources, in order of authority:
 * - US airports (KJFK, KLAX, KSFO, KORD, KATL, KDEN, KDFW, KSEA, KBOS, KMIA):
 *   FAA NASR 28-day subscription, cycle 2026-08-06, APT_RWY_END.csv
 *   LAT_DECIMAL/LONG_DECIMAL. The FAA's own surveyed end positions, public
 *   domain, and the citable source for US threshold geometry.
 * - Non-US airports: OurAirports runways.csv (public domain,
 *   davidmegginson.github.io/ourairports-data), fetched 2026-08-21.
 *
 * All 62 strips matched by ident with zero-padding normalised ("06L" to "6L").
 * `le`/`he` follow the registry id: for "08L/26R", `le` is the 08L threshold
 * and `he` the 26R threshold.
 *
 * Findings from validation, kept because they are about data this project
 * trusted:
 *
 * - The first generation used OurAirports for everything; checking it against
 *   NASR found KORD 09R/27L's east end 3,589 ft short (the 2021 extension),
 *   KJFK 22R off 732 ft and KATL 27R off 496 ft. Displacements along the
 *   runway's own track barely move the extended centreline, which is what
 *   attribution consumes, but the NASR figures remove the caveat for the US
 *   fields. The OMDB length disagreement remains (OurAirports source), so the
 *   non-US rows stay fit for cross-track use and not for touchdown work.
 * - KBOS headings in the registry are wrong, not these coordinates. The
 *   coordinate-derived true bearing of 04L/22R is 020; Boston's magnetic
 *   variation is about 13W, so the magnetic course is 033, and the published
 *   ILS RW04L course is 035. The registry's headingDeg of 44 is off by about
 *   nine degrees and had been silently absorbed by the 20-degree inference
 *   tolerance. KJFK cross-checks exactly (031 true + 13W = 044 magnetic).
 * - Runway names are magnetic and ADS-B tracks are true. Bearings derived
 *   from these coordinates are true, so they compare against ADS-B without
 *   the up-to-13-degree variation error the name-times-ten heuristic carries.
 *
 * Generated by scripts/gen-runway-geometry.py. Regenerate rather than edit.
 */

export type RunwayEnds = {
  /** Threshold of the first-named end, e.g. 08L in "08L/26R". */
  leLat: number;
  leLon: number;
  /** Threshold of the second-named end. */
  heLat: number;
  heLon: number;
};

export const RUNWAY_ENDS: Record<string, Record<string, RunwayEnds>> = {
  KJFK: {
    "04L/22R": { leLat: 40.62202094, leLon: -73.78558413, heLat: 40.65050938, heLon: -73.76332211 },
    "04R/22L": { leLat: 40.62542827, leLon: -73.77034558, heLat: 40.64523697, heLon: -73.75486186 },
    "13L/31R": { leLat: 40.65776444, leLon: -73.79023905, heLat: 40.64372458, heLon: -73.75927272 },
    "13R/31L": { leLat: 40.64836133, leLon: -73.81671472, heLat: 40.62799441, heLon: -73.77178075 },
  },
  KLAX: {
    "06L/24R": { leLat: 33.94911247, leLon: -118.43115986, heLat: 33.95210391, heLon: -118.40194891 },
    "06R/24L": { leLat: 33.94681577, leLon: -118.43466783, heLat: 33.95046327, heLon: -118.399046 },
    "07L/25R": { leLat: 33.93555177, leLon: -118.42206486, heLat: 33.93987788, heLon: -118.37977791 },
    "07R/25L": { leLat: 33.93364938, leLon: -118.41901833, heLat: 33.93736302, heLon: -118.38271391 },
  },
  KSFO: {
    "01L/19R": { leLat: 37.60789786, leLon: -122.3829285, heLat: 37.62648136, heLon: -122.37060941 },
    "01R/19L": { leLat: 37.60632988, leLon: -122.38104075, heLat: 37.62734219, heLon: -122.36711083 },
    "10L/28R": { leLat: 37.62873872, leLon: -122.39339186, heLat: 37.61353361, heLon: -122.35714111 },
    "10R/28L": { leLat: 37.62629111, leLon: -122.39310544, heLat: 37.61171194, heLon: -122.35834916 },
  },
  KORD: {
    "04L/22R": { leLat: 41.98165558, leLon: -87.91391775, heLat: 41.99753711, heLon: -87.89637122 },
    "04R/22L": { leLat: 41.95332716, leLon: -87.8994185, heLat: 41.96992166, heLon: -87.8797433 },
    "09L/27R": { leLat: 42.00283205, leLon: -87.92667608, heLat: 42.0028308, heLon: -87.89908325 },
    "09C/27C": { leLat: 41.98830322, leLon: -87.93157122, heLat: 41.98831033, heLon: -87.89021005 },
    "09R/27L": { leLat: 41.98389366, leLon: -87.93156908, heLat: 41.98390033, heLon: -87.89015488 },
    "10L/28R": { leLat: 41.96899488, leLon: -87.93153172, heLat: 41.96907025, heLon: -87.883729 },
    "10C/28C": { leLat: 41.96570141, leLon: -87.93152161, heLat: 41.96576577, heLon: -87.8918103 },
    "10R/28L": { leLat: 41.95720111, leLon: -87.92786122, heLat: 41.95724625, heLon: -87.90028763 },
  },
  KATL: {
    "08L/26R": { leLat: 33.64953438, leLon: -84.43902563, heLat: 33.64954208, heLon: -84.40945391 },
    "08R/26L": { leLat: 33.64678666, leLon: -84.43836208, heLat: 33.64679477, heLon: -84.40550869 },
    "09L/27R": { leLat: 33.63470444, leLon: -84.44796686, heLat: 33.6347025, heLon: -84.40726611 },
    "09R/27L": { leLat: 33.63181338, leLon: -84.44796577, heLat: 33.63182358, heLon: -84.41840083 },
    "10/28": { leLat: 33.62027244, leLon: -84.44787705, heLat: 33.62028541, heLon: -84.4183155 },
  },
  KDEN: {
    "07/25": { leLat: 39.84094505, leLon: -104.72665638, heLat: 39.84065741, heLon: -104.68393644 },
    "08/26": { leLat: 39.8775558, leLon: -104.66222963, heLat: 39.87724358, heLon: -104.61948552 },
    "16L/34R": { leLat: 39.89703613, leLon: -104.6868055, heLat: 39.86410397, heLon: -104.68718838 },
    "16R/34L": { leLat: 39.89579694, leLon: -104.6960835, heLat: 39.85188683, heLon: -104.69658794 },
    "17L/35R": { leLat: 39.86495241, leLon: -104.64130441, heLat: 39.83201963, heLon: -104.64170983 },
    "17R/35L": { leLat: 39.86124502, leLon: -104.66015447, heLat: 39.82831283, heLon: -104.66055113 },
  },
  KDFW: {
    "13L/31R": { leLat: 32.91255472, leLon: -97.02147836, heLat: 32.89498111, heLon: -97.00084377 },
    "13R/31L": { leLat: 32.90957563, leLon: -97.08313222, heLat: 32.89026988, heLon: -97.06327647 },
    "17C/35C": { leLat: 32.91570669, leLon: -97.02597491, heLat: 32.87887877, heLon: -97.02617166 },
    "17L/35R": { leLat: 32.89832038, leLon: -97.00977861, heLat: 32.8749593, heLon: -97.00990794 },
    "17R/35L": { leLat: 32.91572211, leLon: -97.0298835, heLat: 32.87889452, heLon: -97.03008022 },
    "18L/36R": { leLat: 32.91579958, leLon: -97.05073641, heLat: 32.87897144, heLon: -97.05092588 },
    "18R/36L": { leLat: 32.91581319, leLon: -97.05464552, heLat: 32.87898591, heLon: -97.05483341 },
  },
  KSEA: {
    "16L/34R": { leLat: 47.46379522, leLon: -122.30775022, heLat: 47.43117227, heLon: -122.30803825 },
    "16C/34C": { leLat: 47.46380986, leLon: -122.31098375, heLat: 47.43797127, heLon: -122.31120983 },
    "16R/34L": { leLat: 47.46383636, leLon: -122.31785683, heLat: 47.4405338, heLon: -122.31805805 },
  },
  KBOS: {
    "04L/22R": { leLat: 42.35798825, leLon: -71.01433852, heLat: 42.37829886, heLon: -71.00451386 },
    "04R/22L": { leLat: 42.35105816, leLon: -71.01179388, heLat: 42.37689997, heLon: -70.99929091 },
    "09/27": { leLat: 42.35575416, leLon: -71.01289408, heLat: 42.36021575, heLon: -70.98770211 },
    "14/32": { leLat: 42.3565978, leLon: -71.02327461, heLat: 42.34859902, heLon: -71.00824558 },
    "15R/33L": { leLat: 42.3742708, leLon: -71.01789213, heLat: 42.35465077, heLon: -70.99158605 },
    "15L/33R": { leLat: 42.37319466, leLon: -71.00861241, heLat: 42.36821641, heLon: -71.00194466 },
  },
  KMIA: {
    "08L/26R": { leLat: 25.80289777, leLon: -80.30154188, heLat: 25.80397788, heLon: -80.27543052 },
    "08R/26L": { leLat: 25.80069936, leLon: -80.301433, heLat: 25.80201811, heLon: -80.26953561 },
    "09/27": { leLat: 25.78609502, leLon: -80.31483813, heLat: 25.78773133, heLon: -80.2753253 },
    "12/30": { leLat: 25.79928505, leLon: -80.30228997, heLat: 25.78661733, heLon: -80.27752236 },
  },
  OMDB: {
    "12L/30R": { leLat: 25.26462745666504, leLon: 55.35042190551758, heLat: 25.247709274291992, heLon: 55.38093185424805 },
    "12R/30L": { leLat: 25.252836227416992, leLon: 55.364376068115234, heLat: 25.235919952392578, heLon: 55.39488220214844 },
  },
  EGLL: {
    "09L/27R": { leLat: 51.47749, leLon: -0.489439, heLat: 51.477681, heLon: -0.433227 },
    "09R/27L": { leLat: 51.46478, leLon: -0.486808, heLat: 51.464957, heLon: -0.434048 },
  },
  LPPR: {
    "17/35": { leLat: 41.263301849365234, leLon: -8.685239791870117, heLat: 41.23249816894531, heLon: -8.677200317382812 },
  },
  LPPT: {
    "02/20": { leLat: 38.765678, leLon: -9.144302, heLat: 38.797313, heLon: -9.127376 },
    "17/35": { leLat: 38.78620147705078, leLon: -9.13720989227295, heLat: 38.76499938964844, heLon: -9.131600379943848 },
  },
  EPWA: {
    "11/29": { leLat: 52.171501, leLon: 20.946699, heLat: 52.160999, heLon: 20.9839 },
    "15/33": { leLat: 52.1786, leLon: 20.9559, heLat: 52.149399, heLon: 20.9814 },
  },
  EPKK: {
    "07/25": { leLat: 50.075401306152344, leLon: 19.76810073852539, heLat: 50.0802001953125, heLon: 19.802900314331055 },
  },
  EPPO: {
    "10/28": { leLat: 52.4249, leLon: 16.806101, heLat: 52.418201, heLon: 16.841 },
  },
};
